### ISSUE TITLE
Autoencoder module

### ISSUE THREAD

**Issue by swapsha96** [mirapy-org/MiraPy#6]
Discuss `autoencoder` module here.

This module will initially contain code for 'Astronomical Image Reconstruction using Autoencoders'.

**Comment by akhilsinghal1234** [comment]
declare self.encoded and self.decoded in init.

**Comment by swapsha96** [comment]
@akhilsinghal1234 Please leave your reviews in PR instead of issue.

Also, I declared `self.decoded` but not `encoded` because it wouldn't be put into use. I guess it is only required when we use autoencoders for feature extraction.
